import { Theme } from './types';

export default {
  name: 'blackAndWhite',

  anchor: '#1034a6',
  anchorVisited: '#440381',
  borderDark: '#888c8f',
  borderDarkest: '#000000',
  borderLight: '#dfe0e3',
  borderLightest: '#888c8f',
  canvas: '#ffffff',
  canvasText: '#000000',
  canvasTextDisabled: '#888c8f',
  canvasTextDisabledShadow: '#ffffff',
  canvasTextInvert: '#ffffff',
  checkmark: '#000000',
  checkmarkDisabled: '#888c8f',
  desktopBackground: '#ffffff',
  flatDark: '#9e9e9e',
  flatLight: '#d8d8d8',
  focusSecondary: '#fefe03',
  headerBackground: '#000000',
  headerNotActiveBackground: '#ffffff',
  headerNotActiveText: '#000000',
  headerText: '#ffffff',
  hoverBackground: '#000000',
  material: '#ffffff',
  materialDark: '#9a9e9c',
  materialText: '#000000',
  materialTextDisabled: '#888c8f',
  materialTextDisabledShadow: '#ffffff',
  materialTextInvert: '#ffffff',
  progress: '#000000',
  scale: 2,
  shadow: true,
  tooltip: '#fefbcc'
} as Theme;
