import { Theme } from './types';

export default {
  name: 'lilac',

  anchor: '#1034a6',
  anchorVisited: '#440381',
  borderDark: '#5f549b',
  borderDarkest: '#1c1449',
  borderLight: '#bcb4e9',
  borderLightest: '#d3ccf4',
  canvas: '#ffffff',
  canvasText: '#050608',
  canvasTextDisabled: '#5f549b',
  canvasTextDisabledShadow: '#ffffff',
  canvasTextInvert: '#ffffff',
  checkmark: '#050608',
  checkmarkDisabled: '#5f549b',
  desktopBackground: '#000000',
  flatDark: '#9e9e9e',
  flatLight: '#d8d8d8',
  focusSecondary: '#fefe03',
  headerBackground: '#5e4dba',
  headerNotActiveBackground: '#7f7f81',
  headerNotActiveText: '#ced0cf',
  headerText: '#ffffff',
  hoverBackground: '#5e4dba',
  material: '#b1a7df',
  materialDark: '#9a9e9c',
  materialText: '#050608',
  materialTextDisabled: '#5f549b',
  materialTextDisabledShadow: '#ffffff',
  materialTextInvert: '#ffffff',
  progress: '#5e4dba',
  tooltip: '#fefbcc'
} as Theme;
