import { Theme } from './types';

export default {
  name: 'water',

  anchor: '#72b3b4',
  anchorVisited: '#440381',
  borderDark: '#888c8f',
  borderDarkest: '#050608',
  borderLight: '#dfe0e3',
  borderLightest: '#ffffff',
  canvas: '#ffffff',
  canvasText: '#050608',
  canvasTextDisabled: '#888c8f',
  canvasTextDisabledShadow: '#ffffff',
  canvasTextInvert: '#ffffff',
  checkmark: '#050608',
  checkmarkDisabled: '#888c8f',
  desktopBackground: '#3a6ea5',
  flatDark: '#9e9e9e',
  flatLight: '#d8d8d8',
  focusSecondary: '#fefe03',
  headerBackground: '#72b3b4',
  headerNotActiveBackground: '#9a9e9c',
  headerNotActiveText: '#ced0cf',
  headerText: '#ffffff',
  hoverBackground: '#72b3b4',
  material: '#ced0cf',
  materialDark: '#9a9e9c',
  materialText: '#050608',
  materialTextDisabled: '#888c8f',
  materialTextDisabledShadow: '#ffffff',
  materialTextInvert: '#ffffff',
  progress: '#72b3b4',
  scale: 2,
  shadow: true,
  tooltip: '#fefbcc'
} as Theme;
